Isecicd272&273: Fix import task template with empty command and 403 error message
boomerang-io/flow.client.web pull request #176
Opened 2023-02-15 02:38 UTC by Amy0511

## Context

Related Issues(s): 

Build Number: 

## Checklist:

- [ ] Verified in an integrated environment
- [ ] Unit and integration tests passing
- [ ] Semantic HTML with accessibility support
- [ ] No linting, test console, or browser console errors (best effort)
- [ ] JSDoc comment blocks for complex code

## PR Review Guidance

## Additional Info

2023-02-21 01:17 UTC, Amy0511 commented
@timrbula @BenjaminRuby Could you please help to review the code? It fixed the bug of import task template with empty command error and also fixed the 403 error message.

2023-02-22 03:58 UTC, shenqinb-star approved these changes

2023-02-22 20:39 UTC, timrbula requested changes
Added the same question twice about formatting the error message. Otherwise, things look good

2023-02-22 20:39 UTC, timrbula commented on src/Features/TaskTemplates/Sidenav/AddTaskTemplate/AddTaskTemplate.tsx
> +        let errorTitle = err.toString();
We have a `formatErrorMessage` util, did yall try using that for formatting the error? 

`import { formatErrorMessage } from "@boomerang-io/utils";`

2023-02-22 20:39 UTC, timrbula commented on src/Features/ManageTeamTasks/Sidenav/AddTaskTemplate/AddTaskTemplate.tsx
> +        let errorTitle = err.toString();
We have a `formatErrorMessage` util, did yall try using that for formatting the error? 

`import { formatErrorMessage } from "@boomerang-io/utils";`

2023-02-23 02:49 UTC, shenqinb-star approved these changes

2023-02-23 02:49 UTC, Amy0511 commented
@timrbula Could you please help to review it again? I changed to use `formatErrorMessage`. Thanks!

2023-02-24 06:21 UTC, timrbula approved these changes

2023-02-24 17:37 UTC, merged