Fix [226] Yaml Import Error
boomerang-io/flow.client.web pull request #91
Opened 2021-09-20 19:27 UTC by LucasGrimauth

## Context

Related Issues(s): https://app.zenhub.com/workspaces/boomerang-flow-5f9600754a5aa9001521ccc1/issues/boomerang-io/roadmap/226

Build Number: 

## Checklist:

- [ ] Verified in an integrated environment
- [ ] Unit and integration tests passing
- [ ] Semantic HTML with accessibility support
- [ ] No linting, test console, or browser console errors (best effort)
- [ ] JSDoc comment blocks for complex code

## PR Review Guidance
If the file doesn't have a description, the app errors when trying to get the length of the undefined description in one of the inputs, so would be good to merge this with main as well.
Also updated the messages to use InlineNotification.

2021-09-20 20:39 UTC, Okisa requested changes
Hi Lucas! Looking good!
Can you add the same changes for Team Tasks?

2021-09-20 20:40 UTC, BenjaminRuby commented
> Can you add the same changes for Team Tasks?

Good call @Okisa - we consolidated that as part of the cleanup work under 3.4, correct?

2021-09-21 18:27 UTC, Okisa submitted a review, later dismissed
All good! Thanks Lucas!

2021-10-05 19:44 UTC, BenjaminRuby approved these changes

2021-10-05 19:45 UTC, merged